<?php

use App\Domains\Accounts\Application\RolePresetService;
use App\Domains\Accounts\Models\CompanySetting;
use App\Domains\Accounts\Models\User;
use App\Domains\Metadata\Models\CustomField;
use App\Domains\Purchases\Events\RecurringCostFailed;
use App\Domains\Purchases\Models\Bill;
use App\Domains\Purchases\Models\Expense;
use App\Domains\Purchases\Models\ExpenseCategory;
use App\Domains\Purchases\Models\RecurringCost;
use App\Platform\Notifications\AppNotification;
use App\Platform\Notifications\Channels\CompanyDatabaseChannel;
use App\Support\Recurrence\RecurrenceRunner;
use Carbon\Carbon;
use Illuminate\Notifications\Events\NotificationSending;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Notification;
use Laravel\Sanctum\Sanctum;
use Silber\Bouncer\BouncerFacade;

use function Pest\Laravel\artisan;

/**
 * Recurring bills and expenses: set up through the API, generated by the
 * shared recurrence runner.
 */
beforeEach(function () {
    purchaseFixtures($this);
    CompanySetting::setSettings(['time_zone' => 'UTC'], $this->companyId);
    Carbon::setTestNow('2026-06-15 12:00:00');
});

afterEach(fn () => Carbon::setTestNow());

function recurringBillPayload($test, array $overrides = []): array
{
    $bill = purchaseBillPayload($test, 5000);

    return [
        'name' => 'Office rent',
        'supplier_id' => $test->supplier->id,
        'mode' => 'BILL',
        'frequency' => '0 0 1 * *',
        'starts_at' => '2026-06-15',
        'limit_by' => 'NONE',
        'due_days' => 14,
        'template' => ['currency_id' => $bill['currency_id'], 'exchange_rate' => 1, 'items' => $bill['items']],
        ...$overrides,
    ];
}

/**
 * A schedule whose next run is set back, as if the scheduler had been down.
 */
function overdueSchedule($test, array $overrides = [], string $nextRun = '2026-04-01 00:00:00'): RecurringCost
{
    $id = $test->postJson('/api/v1/recurring-costs', recurringBillPayload($test, $overrides))->assertSuccessful()->json('data.id');
    RecurringCost::query()->whereKey($id)->update(['next_run_at' => $nextRun]);

    return RecurringCost::findOrFail($id);
}

test('a new schedule first runs on its first occurrence from today', function () {
    $this->postJson('/api/v1/recurring-costs', recurringBillPayload($this))
        ->assertSuccessful()
        ->assertJsonPath('data.status', 'ACTIVE')
        ->assertJsonPath('data.next_run_at', '2026-07-01 00:00:00');

    $this->postJson('/api/v1/recurring-costs', recurringBillPayload($this, ['starts_at' => '2026-09-01']))
        ->assertJsonPath('data.next_run_at', '2026-09-01 00:00:00');
});

test('missed runs are each generated as a bill dated its own day', function () {
    $schedule = overdueSchedule($this);

    artisan('recurring-costs:generate')->assertSuccessful();

    $bills = Bill::query()->orderBy('document_date')->get();

    expect($bills->pluck('document_date')->all())->toBe(['2026-04-01', '2026-05-01', '2026-06-01'])
        ->and($bills->pluck('due_date')->all())->toBe(['2026-04-15', '2026-05-15', '2026-06-15'])
        ->and($bills->pluck('status')->unique()->all())->toBe(['OPEN'])
        ->and((int) $bills->first()->total)->toBe(5000)
        ->and($schedule->fresh()->next_run_at)->toBe('2026-07-01 00:00:00')
        ->and($schedule->occurrences()->count())->toBe(3);

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->count())->toBe(3);
});

test('draft mode creates bills to review first', function () {
    overdueSchedule($this, ['create_as_draft' => true], '2026-06-01 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->sole()->status)->toBe('DRAFT');
});

test('a recurring expense is recorded as paid on its day', function () {
    overdueSchedule($this, [
        'mode' => 'EXPENSE',
        'template' => ['amount' => 1999, 'currency_id' => $this->currencyId, 'exchange_rate' => 1, 'expense_category_id' => $this->category->id],
    ], '2026-06-01 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();

    $expense = Expense::query()->sole();

    expect($expense->expense_date)->toStartWith('2026-06-01')
        ->and((int) $expense->amount)->toBe(1999)
        ->and($expense->supplier_id)->toBe($this->supplier->id)
        ->and(Bill::query()->count())->toBe(0);
});

test('a count limit completes the schedule, and raising it reactivates it', function () {
    $schedule = overdueSchedule($this, ['limit_by' => 'COUNT', 'limit_count' => 2]);

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->count())->toBe(2)
        ->and($schedule->fresh()->status)->toBe('COMPLETED');

    // Months later the limit is raised: the schedule carries on from today
    // instead of making up the runs it sat out.
    Carbon::setTestNow('2026-09-15 12:00:00');
    $this->putJson('/api/v1/recurring-costs/'.$schedule->id, recurringBillPayload($this, ['limit_by' => 'COUNT', 'limit_count' => 5]))
        ->assertSuccessful()
        ->assertJsonPath('data.status', 'ACTIVE')
        ->assertJsonPath('data.next_run_at', '2026-10-01 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();
    expect(Bill::query()->count())->toBe(2);
});

test('a paused schedule made active from the form skips the runs it sat out', function () {
    $schedule = overdueSchedule($this, ['status' => 'ON_HOLD']);

    $this->putJson('/api/v1/recurring-costs/'.$schedule->id, recurringBillPayload($this, ['status' => 'ACTIVE']))
        ->assertSuccessful()
        ->assertJsonPath('data.status', 'ACTIVE')
        ->assertJsonPath('data.next_run_at', '2026-07-01 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();
    expect(Bill::query()->count())->toBe(0);
});

test('a paused schedule makes nothing, and resuming keeps today but skips the paused runs', function () {
    Carbon::setTestNow('2026-06-01 09:00:00');
    $schedule = overdueSchedule($this);

    $this->postJson('/api/v1/recurring-costs/'.$schedule->id.'/actions', ['action' => 'pause'])->assertJsonPath('data.status', 'ON_HOLD');
    artisan('recurring-costs:generate')->assertSuccessful();
    expect(Bill::query()->count())->toBe(0);

    $this->postJson('/api/v1/recurring-costs/'.$schedule->id.'/actions', ['action' => 'resume'])
        ->assertJsonPath('data.status', 'ACTIVE')
        ->assertJsonPath('data.next_run_at', '2026-06-01 00:00:00');
    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->sole()->document_date)->toBe('2026-06-01');
});

test('a failing run keeps its day, tells the creator once and recovers', function () {
    Notification::fake();
    $schedule = overdueSchedule($this, ['notify_creator' => true], '2026-06-01 00:00:00');
    $this->supplier->update(['enabled' => false]);

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->count())->toBe(0)
        ->and($schedule->fresh()->last_error)->toBe('purchase_supplier_inactive')
        ->and($schedule->fresh()->next_run_at)->toBe('2026-06-01 00:00:00');
    Notification::assertSentTo($this->user, AppNotification::class, fn (AppNotification $notice) => $notice->message->type === 'recurring_cost_failed'
        && $notice->message->params['reason'] === 'errors.purchase_supplier_inactive'
        && $notice->via($this->user) === [CompanyDatabaseChannel::class, 'mail']);

    // Within the hour it is left alone; after it, it is tried again without a second notice.
    Carbon::setTestNow('2026-06-15 12:30:00');
    artisan('recurring-costs:generate')->assertSuccessful();
    Carbon::setTestNow('2026-06-15 14:00:00');
    artisan('recurring-costs:generate')->assertSuccessful();
    Notification::assertSentToTimes($this->user, AppNotification::class, 1);

    $this->supplier->update(['enabled' => true]);
    Carbon::setTestNow('2026-06-15 16:00:00');
    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->count())->toBe(1)
        ->and($schedule->fresh()->last_error)->toBeNull();
    Notification::assertSentTo($this->user, AppNotification::class, fn (AppNotification $notice) => $notice->message->type === 'recurring_cost_generated'
        && $notice->message->variant === 'bill'
        && $notice->message->url === '/admin/bills/'.Bill::query()->sole()->id.'/view');
});

test('nobody is told about a generated record when the schedule does not ask for it', function () {
    Notification::fake();
    overdueSchedule($this, [], '2026-06-01 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();

    Notification::assertNothingSent();
});

test('a failure is told even when the schedule does not ask about generated records', function () {
    Notification::fake();
    overdueSchedule($this, [], '2026-06-01 00:00:00');
    $this->supplier->update(['enabled' => false]);

    artisan('recurring-costs:generate')->assertSuccessful();

    Notification::assertSentTo($this->user, AppNotification::class, fn (AppNotification $notice) => $notice->message->type === 'recurring_cost_failed');
});

test('bill custom field answers carry over to each generated bill', function () {
    $field = CustomField::factory()->create(['company_id' => $this->companyId, 'model_type' => 'Bill', 'type' => 'Input', 'label' => 'Cost centre', 'is_required' => false, 'placement' => 'internal', 'order' => 0]);
    $payload = recurringBillPayload($this);
    $payload['template']['customFields'] = [['id' => $field->id, 'value' => 'HQ']];
    $id = $this->postJson('/api/v1/recurring-costs', $payload)->assertSuccessful()->json('data.id');
    RecurringCost::query()->whereKey($id)->update(['next_run_at' => '2026-06-01 00:00:00']);

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->sole()->fields()->first()->defaultAnswer)->toBe('HQ');
});

test('what a schedule still uses cannot be deleted', function () {
    $category = ExpenseCategory::create(['company_id' => $this->companyId, 'name' => 'Rent']);
    $payload = recurringBillPayload($this);
    $payload['template']['items'][0]['expense_category_id'] = $category->id;
    $this->postJson('/api/v1/recurring-costs', $payload)->assertSuccessful();

    $this->deleteJson('/api/v1/categories/'.$category->id)->assertJsonPath('error', 'expense_attached');
    expect($category->fresh())->not->toBeNull();
});

test('Manager can set up schedules and Read only can only see them', function () {
    app(RolePresetService::class)->applyDefaults();
    $member = function (string $role) {
        $user = User::factory()->create(['role' => 'user']);
        $user->companies()->attach($this->companyId);
        BouncerFacade::scope()->onceTo($this->companyId, fn () => $user->assign($role));
        BouncerFacade::refresh();

        return $user;
    };

    Sanctum::actingAs($member('preset:manager'));
    $this->postJson('/api/v1/recurring-costs', recurringBillPayload($this))->assertSuccessful();

    Sanctum::actingAs($member('preset:read-only'));
    $this->getJson('/api/v1/recurring-costs')->assertOk()->assertJsonCount(1, 'data');
    $this->postJson('/api/v1/recurring-costs', recurringBillPayload($this))->assertForbidden();
});

test('the detail lists what the schedule generated', function () {
    $schedule = overdueSchedule($this, [], '2026-05-01 00:00:00');
    artisan('recurring-costs:generate')->assertSuccessful();

    $this->getJson('/api/v1/recurring-costs/'.$schedule->id)
        ->assertOk()
        ->assertJsonCount(2, 'data.occurrences')
        ->assertJsonPath('data.occurrences.0.scheduled_for', '2026-06-01')
        ->assertJsonPath('data.occurrences.0.record_type', 'bill')
        ->assertJsonPath('data.occurrences.0.amount', 5000);
});

test('a mail server that is down fails neither the run nor the runs after it', function () {
    Event::listen(NotificationSending::class, fn () => throw new RuntimeException('SMTP is down'));
    $travel = ExpenseCategory::create(['company_id' => $this->companyId, 'name' => 'Travel']);
    $broken = overdueSchedule($this, [
        'mode' => 'EXPENSE',
        'notify_creator' => true,
        'template' => ['amount' => 1999, 'currency_id' => $this->currencyId, 'exchange_rate' => 1, 'expense_category_id' => $travel->id],
    ], '2026-06-01 00:00:00');
    $working = overdueSchedule($this, ['notify_creator' => true], '2026-05-01 00:00:00');
    // Taken away underneath the expense schedule, past the deletion guard.
    ExpenseCategory::query()->whereKey($travel->id)->delete();

    artisan('recurring-costs:generate')->assertSuccessful();

    expect($broken->fresh()->last_error)->toBe('purchase_recurring_template_invalid')
        ->and(Bill::query()->count())->toBe(2)
        ->and($working->fresh()->last_error)->toBeNull()
        ->and($working->fresh()->next_run_at)->toBe('2026-07-01 00:00:00');
});

test('a failure from a form rule is shown as a template to fix, in words', function () {
    $errors = json_decode(file_get_contents(base_path('lang/en.json')), true)['errors'];

    expect($errors)->toHaveKey('purchase_recurring_template_invalid');
});

test('someone no longer in the company is not told about its schedules', function () {
    Notification::fake();
    overdueSchedule($this, ['notify_creator' => true], '2026-06-01 00:00:00');
    $this->user->companies()->detach($this->companyId);

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->count())->toBe(1);
    Notification::assertNothingSent();
});

test('expense custom field answers are required like the form and carry over', function () {
    $field = CustomField::factory()->create(['company_id' => $this->companyId, 'model_type' => 'Expense', 'type' => 'Input', 'label' => 'Project', 'is_required' => true, 'placement' => 'internal', 'order' => 0]);
    $payload = recurringBillPayload($this, [
        'mode' => 'EXPENSE',
        'template' => ['amount' => 1999, 'currency_id' => $this->currencyId, 'exchange_rate' => 1, 'expense_category_id' => $this->category->id],
    ]);

    $this->postJson('/api/v1/recurring-costs', $payload)->assertUnprocessable();

    $payload['template']['customFields'] = [['id' => $field->id, 'value' => 'Apollo']];
    $id = $this->postJson('/api/v1/recurring-costs', $payload)->assertSuccessful()->json('data.id');
    RecurringCost::query()->whereKey($id)->update(['next_run_at' => '2026-06-01 00:00:00']);

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Expense::query()->sole()->fields()->first()->defaultAnswer)->toBe('Apollo');
});

test('saving a failing schedule clears its failure, and a new reason is told again', function () {
    Notification::fake();
    $schedule = overdueSchedule($this, [
        'mode' => 'EXPENSE',
        'notify_creator' => true,
        'template' => ['amount' => 1999, 'currency_id' => $this->currencyId, 'exchange_rate' => 1, 'expense_category_id' => $this->category->id],
    ], '2026-06-01 00:00:00');
    $this->supplier->update(['enabled' => false]);

    artisan('recurring-costs:generate')->assertSuccessful();
    expect($schedule->fresh()->last_error)->toBe('purchase_supplier_inactive');

    // A different reason after the retry window is a new notice.
    $this->supplier->update(['enabled' => true]);
    ExpenseCategory::query()->whereKey($this->category->id)->delete();
    Carbon::setTestNow('2026-06-15 14:00:00');
    artisan('recurring-costs:generate')->assertSuccessful();
    expect($schedule->fresh()->last_error)->toBe('purchase_recurring_template_invalid');
    Notification::assertSentToTimes($this->user, AppNotification::class, 2);

    // Fixing and saving it lets the very next run go ahead.
    $category = ExpenseCategory::create(['company_id' => $this->companyId, 'name' => 'Rent']);
    $this->putJson('/api/v1/recurring-costs/'.$schedule->id, recurringBillPayload($this, [
        'mode' => 'EXPENSE',
        'notify_creator' => true,
        'template' => ['amount' => 1999, 'currency_id' => $this->currencyId, 'exchange_rate' => 1, 'expense_category_id' => $category->id],
    ]))->assertSuccessful()->assertJsonPath('data.last_error', null);
    $schedule->refresh()->forceFill(['next_run_at' => '2026-06-01 00:00:00'])->save();

    Carbon::setTestNow('2026-06-15 14:01:00');
    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Expense::query()->count())->toBe(1);
});

test('a failure handler that throws does not stop the schedules after it', function () {
    Event::listen(RecurringCostFailed::class, fn () => throw new RuntimeException('Listener is broken'));
    $schedule = overdueSchedule($this, ['notify_creator' => true], '2026-06-01 00:00:00');
    $this->supplier->update(['enabled' => false]);
    artisan('recurring-costs:generate')->assertSuccessful();

    expect($schedule->fresh()->last_error)->toBe('purchase_supplier_inactive');
});

function expenseTemplate($test): array
{
    return ['amount' => 1999, 'currency_id' => $test->currencyId, 'exchange_rate' => 1, 'expense_category_id' => $test->category->id];
}

test('a schedule far behind catches up 100 runs a pass and never twice', function () {
    // 151 daily runs, 16 January to 15 June.
    $schedule = overdueSchedule($this, ['mode' => 'EXPENSE', 'frequency' => '0 0 * * *', 'template' => expenseTemplate($this)], '2026-01-16 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();
    expect(Expense::query()->count())->toBe(100);

    artisan('recurring-costs:generate')->assertSuccessful();
    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Expense::query()->count())->toBe(151)
        ->and($schedule->occurrences()->count())->toBe(151)
        ->and(Expense::query()->min('expense_date'))->toStartWith('2026-01-16')
        ->and(Expense::query()->max('expense_date'))->toStartWith('2026-06-15')
        ->and($schedule->fresh()->next_run_at)->toBe('2026-06-16 00:00:00');
});

test('a date limit stops a schedule after its last day, even when it is behind', function () {
    // Set up in March; the scheduler is next run in June.
    Carbon::setTestNow('2026-03-15 12:00:00');
    $schedule = overdueSchedule($this, ['starts_at' => '2026-03-01', 'limit_by' => 'DATE', 'limit_date' => '2026-05-15']);
    Carbon::setTestNow('2026-06-15 12:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->orderBy('document_date')->pluck('document_date')->all())->toBe(['2026-04-01', '2026-05-01'])
        ->and($schedule->fresh()->status)->toBe('COMPLETED');
});

test('a failed schedule waits out the hour unless its failure is forgotten', function () {
    $schedule = overdueSchedule($this, [], '2026-06-01 00:00:00');
    $this->supplier->update(['enabled' => false]);
    artisan('recurring-costs:generate')->assertSuccessful();

    $this->supplier->update(['enabled' => true]);
    artisan('recurring-costs:generate')->assertSuccessful();
    expect(Bill::query()->count())->toBe(0);

    app(RecurrenceRunner::class)->forgetFailure($schedule);
    artisan('recurring-costs:generate')->assertSuccessful();
    expect(Bill::query()->count())->toBe(1);
});

test('a bill on the 31st is made in the months that have one', function () {
    overdueSchedule($this, ['starts_at' => '2026-01-01', 'frequency' => '0 0 31 * *'], '2026-01-31 00:00:00');

    artisan('recurring-costs:generate')->assertSuccessful();
    artisan('recurring-costs:generate')->assertSuccessful();

    expect(Bill::query()->orderBy('document_date')->pluck('document_date')->all())->toBe(['2026-01-31', '2026-03-31', '2026-05-31']);
});

test('a daily expense makes one record a day through both clock changes', function () {
    CompanySetting::setSettings(['time_zone' => 'Europe/Skopje'], $this->companyId);
    Carbon::setTestNow('2026-10-27 12:00:00');
    // 02:30 in Skopje: skipped by the spring change, repeated by the autumn one.
    $schedule = overdueSchedule($this, ['mode' => 'EXPENSE', 'frequency' => '30 2 * * *', 'starts_at' => '2026-10-27', 'template' => expenseTemplate($this)], '2026-03-27 01:30:00');

    artisan('recurring-costs:generate')->assertSuccessful();
    artisan('recurring-costs:generate')->assertSuccessful();
    artisan('recurring-costs:generate')->assertSuccessful();

    $dates = Expense::query()->orderBy('expense_date')->pluck('expense_date')->map(fn ($date) => substr($date, 0, 10));

    // 27 March to 27 October: 215 days, each once.
    expect($dates)->toHaveCount(215)
        ->and($dates->unique())->toHaveCount(215)
        ->and($dates->contains('2026-03-29'))->toBeTrue()
        ->and($dates->contains('2026-10-25'))->toBeTrue()
        ->and($schedule->occurrences()->count())->toBe(215);
});
