# Big thanks to https://github.com/files-community/Files/ for a template of the feature_request

name: Feature Request
labels:
  - feature request
  - triage
type: Feature
projects: ['InvoiceShelf/2']
assignees:
  - rihards-simanovics
description: >-
  This project thrives from differentiation from competing apps. Suggest an idea
  for InvoiceShelf.
body:
  # Tip to warn of checking for existing issues
  - type: markdown
    attributes:
      value: >
        > [!TIP]

        >Have you checked for similar feature requests? There's a possibility
        your suggestion is already being tracked. Please do a thorough search
        before creating a new issue.

  # Ask user to confirm they've tried to fix or research the issue before
  # posting a bug report.
  - type: checkboxes
    id: confirm-read-documentation
    attributes:
      label: Issue filing prerequisites
      description: 'Prior to filing an issue please confirm that:'
      options:
        - label: I've checked the [documentation](https://docs.invoiceshelf.com/).
          required: true
        - label: I've looked for similar issues with feature requests both Open and Closed.
          required: true
        - label: >-
            I've tried clearing both cache and cookies in my browser or tried
            opening the app in the Incognito/InPrivate window.
          required: true

  # Description
  - type: textarea
    id: what-feature
    attributes:
      label: What feature or improvement do you think would benefit InvoiceShelf?
      description: Please include your use case
      placeholder: >-
        I propose that feature J be implemented as I believe it will greatly benefit the application.
    validations:
      required: true

  # Tooltip about Requirements
  - type: markdown
    attributes:
      value: >
        ---


        Please include a list of changes required to make this improvement. A good
        rule of thumb is to start your proposal with no more than 7 high-level
        requirements.

  # Requirements
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Describe all the requirements to make your idea happen.
      placeholder: >-
        - This proposal will accomplish X

        - This proposal will accomplish Y

        - This proposal will accomplish Z
    validations:
      required: true

  # InvoiceShelf Version
  - type: input
    id: invoiceshelf_version
    attributes:
      label: App Version
      description: Which version of InvoiceShelf are you currently using?
      placeholder: v0.0.0
    validations:
      required: true

  # Additional Comments
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: >-
        Additional information, comments or screenshots about the feature
        request.
