# install dependencies
RUN apt update && apt install -y \
    libpng-dev \
    zlib1g-dev \
    libxml2-dev \
    libonig-dev \
    mariadb-client \
    webp \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install xml
